# Generated by Django 4.2.13 on 2026-05-23 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predictions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('phone_last4', models.CharField(blank=True, max_length=4)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('preferred_channel', models.CharField(choices=[('sms', 'SMS Only'), ('email', 'Email Only'), ('both', 'SMS and Email')], default='sms', max_length=10)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_secret', models.CharField(blank=True, max_length=32)),
                ('subscription_area', models.CharField(default='Maga', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FloodAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('alert_type', models.CharField(choices=[('automated', 'Automated by ML Model'), ('manual', 'Manual by Authority')], default='automated', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('message_fr', models.TextField()),
                ('message_en', models.TextField(blank=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sms_sent', models.IntegerField(default=0)),
                ('email_sent', models.IntegerField(default=0)),
                ('push_sent', models.IntegerField(default=0)),
                ('is_all_clear', models.BooleanField(default=False)),
                ('risk_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='predictions.riskassessment')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='alerts.floodalert')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='alerts.alertsubscriber')),
            ],
            options={
                'unique_together': {('alert', 'subscriber', 'channel')},
            },
        ),
    ]
