# Generated by Django 4.2.13 on 2026-05-23 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloodEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('affected_area_km2', models.FloatField(default=0.0)),
                ('affected_population', models.IntegerField(default=0)),
                ('max_water_level_m', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('flood_extent_geojson', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['event_date'], name='floods_floo_event_d_e36531_idx'), models.Index(fields=['severity'], name='floods_floo_severit_eff756_idx')],
            },
        ),
    ]
